### ISSUE TITLE
编译 macOS 版本

### ISSUE THREAD

**Issue by zijianjiao2017** [tonquer/waifu2x-ncnn-vulkan-python#1]
我尝试了在 mac 上编译本项目（ [Here](https://github.com/zijianjiao2017/waifu2x-ncnn-vulkan-python-macos) ），
能跑 demo（虽然是用 CPU，但是理论上如果设备有 AMD 独显的话就能用 GPU 跑）
![image](https://user-images.githubusercontent.com/61231083/116806638-0a6c9e00-ab61-11eb-8603-77ec6bdae8b5.png)
![image](https://user-images.githubusercontent.com/61231083/116806625-f4f77400-ab60-11eb-91d2-857ff0e297b3.png)

毕竟原项目（ [https://github.com/nihui/waifu2x-ncnn-vulkan](waifu2x-ncnn-vulkan) ） 就是可以在 mac 上面运行的嘛，
但是....
![image](https://user-images.githubusercontent.com/61231083/116806771-c4fca080-ab61-11eb-904e-b9146392657f.png)

于是目前核显好像就只能用 CPU 跑了...qwq（速度慢的1p  ）
（另外没有编译 ARM64 的，因为懒以及我没有 ARM Mac(逃

**Comment by tonquer** [comment]
是的，应该是可以支持Mac的，但是因为我没有mac设备 所有没有去编译

**Comment by zijianjiao2017** [comment]
> 是的，应该是可以支持Mac的，但是因为我没有mac设备 所有没有去编译

O ok

**Comment by zijianjiao2017** [comment]
核显有希望了 https://github.com/nihui/waifu2x-ncnn-vulkan/issues/146

**Comment by zijianjiao2017** [comment]
~~wssb~~

原来是因为我没有安装 MoltenVK SDK，那个东西就好像驱动一样，没有装就会缺 dylib，现在不会再报`vkCreateInstance failed -9`了，而且 Vulkan Hardware Capability Viewer 也能正常打开了，但是 Waifu2x 会 Segfault，还是要等 ncnn 的大佬那边修复 qaq

**Comment by zijianjiao2017** [comment]
![image](https://user-images.githubusercontent.com/61231083/117085144-92c68b00-ad7b-11eb-941c-f0d6ac2af2ed.png)

![image](https://user-images.githubusercontent.com/61231083/117085096-73c7f900-ad7b-11eb-8274-3af83b5ce1af.png)
![image](https://user-images.githubusercontent.com/61231083/117085130-8b9f7d00-ad7b-11eb-8b9c-1b8ac60d8382.png)

**Comment by zijianjiao2017** [comment]
> ~wssb~
> 
> 原来是因为我没有安装 MoltenVK SDK，那个东西就好像驱动一样，没有装就会缺 dylib，现在不会再报`vkCreateInstance failed -9`了，而且 Vulkan Hardware Capability Viewer 也能正常打开了，但是 Waifu2x 会 Segfault，还是要等 ncnn 的大佬那边修复 qaq

ncnn 的大佬已经修复了

**Comment by zijianjiao2017** [comment]
> ~wssb~
> 
> 原来是因为我没有安装 MoltenVK SDK，那个东西就好像驱动一样，没有装就会缺 dylib，现在不会再报`vkCreateInstance failed -9`了，而且 Vulkan Hardware Capability Viewer 也能正常打开了，但是 Waifu2x 会 Segfault，还是要等 ncnn 的大佬那边修复 qaq

btw, 之前缺少 dylib 应该是因为我在 cmake build 的时候忘记加 -DUSE_STATIC_MOLTENVK=ON 这个选项, 现在没这个问题了
![image](https://user-images.githubusercontent.com/61231083/120063785-86dc9900-c09b-11eb-85d6-76fbe3af2f79.png)
