### ISSUE TITLE
Linux 下 Python 解释器没有立即退出

### ISSUE THREAD

**Issue by zijianjiao2017** [tonquer/waifu2x-ncnn-vulkan-python#6]
## 问题
我在 Ubuntu 下调试时, 执行 `exit()` 之后 Python 解释器 (进程) 没有立即退出.
跑示例脚本 `test.py` 的时候也会遇到同样的问题. (于是现在最简单的退出方式可能是 ^c / ^d)..

感觉这个行为就像是仍有一个或者多个线程没有退出所导致的..
但是貌似在其他平台上 (Windows, macOS) 不能复现..
## 复现过程
````python
import waifu2x
waifu2x.init()
waifu2x.initSet(0, xxx)
exit()
````

https://user-images.githubusercontent.com/61231083/121061203-23b6d900-c7f6-11eb-95fa-e0ad00b8d527.mov

**Comment by tonquer** [comment]
exit前 你调用waifu2x.stop()试试。
不行的话可能是Linux线程退出顺序的问题

**Comment by zijianjiao2017** [comment]
> exit前 你调用waifu2x.stop()试试。
> 不行的话可能是Linux线程退出顺序的问题

stop() 好像也没有用啊（ ~~其实之前我试过了~~
![image](https://user-images.githubusercontent.com/61231083/121132279-86928980-c863-11eb-8e4a-ac9b2bd0944b.png)

**Comment by tonquer** [comment]
有空我再调试一下

**Comment by tonquer** [comment]
已经修复了
